"""Adicionar itens no pedido

Revision ID: 13dc7a19356c
Revises: bf8bf919fe5f
Create Date: 2026-06-18 12:42:52.823387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13dc7a19356c'
down_revision: Union[str, Sequence[str], None] = 'bf8bf919fe5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
